import { menuImage } from "@/lib/content/menu";
import { DESSERT_BATCH_SIZES, BEVERAGE_BATCH_SIZES } from "./batches";
import { STANDARD_BEVERAGE_EQUIPMENT, STANDARD_DESSERT_EQUIPMENT } from "./equipment";
import type { Recipe } from "./types";

export const DESSERT_RECIPES: Recipe[] = [
  {
    slug: "ooey-gooey-butter-cake",
    name: "PJ's Ooey Gooey Butter Cake",
    category: "Desserts",
    difficulty: "Intermediate",
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    holdTimeMinutes: 480,
    shelfLife: "4 days at room temp in covered pan",
    storageInstructions: "Store in 9×13 hotel pan covered. Cut to order. Do not refrigerate — texture sets too firm.",
    servingTemperature: "Room temp or slightly warmed",
    internalTemps: [{ item: "Center set", tempF: 200, note: "Edges golden, center just set" }],
    equipment: [...STANDARD_DESSERT_EQUIPMENT],
    description:
      "St. Louis-born, Atlanta perfected. A dense butter cake base topped with a crackled, custardy cream cheese layer — rich, buttery, dangerously good.",
    image: menuImage("ooey-gooey-butter-cake"),
    usageCount: 324,
    batchSizes: DESSERT_BATCH_SIZES,
    ingredients: [
      { name: "Yellow Cake Mix", amount: 4, unit: "lb", costPerUnit: 0.85 },
      { name: "Unsalted Butter", amount: 3, unit: "lb", prepNotes: "Softened", costPerUnit: 3.8 },
      { name: "Eggs", amount: 12, unit: "ea", costPerUnit: 0.22 },
      { name: "Cream Cheese", amount: 4, unit: "lb", prepNotes: "Softened", costPerUnit: 3.2 },
      { name: "Powdered Sugar", amount: 6, unit: "lb", costPerUnit: 0.72 },
      { name: "Vanilla Extract", amount: 4, unit: "oz", costPerUnit: 1.2 },
      { name: "Kosher Salt", amount: 0.5, unit: "oz", costPerUnit: 0.08 },
    ],
    steps: [
      "Mix cake mix, 1 lb butter, and 2 eggs for crust. Press into greased 9×13 pans.",
      "Beat cream cheese, remaining butter, powdered sugar, eggs, vanilla, and salt until smooth.",
      "Pour topping over crust. Bake 325°F, 40–45 min — edges golden, center wobbly.",
      "Cool completely before cutting. Dust with powdered sugar.",
    ],
    chefNotes: {
      tips: ["Do not overbake — center should jiggle slightly.", "Use offset spatula for clean cuts."],
      criticalControlPoints: ["Cool fully before cutting", "Label contains dairy and eggs"],
      commonMistakes: ["Overbaking — dry, not gooey", "Cold cream cheese — lumpy topping"],
      textureGuide: "Crisp shortbread base, fudgy custard top with crackled surface.",
      colorGuide: "Golden brown edges, pale yellow center with powdered sugar dust.",
      tasteGuide: "Pure butter and vanilla sweetness — rich but not cloying.",
    },
    nutrition: { calories: 420, proteinG: 5, fatG: 24, carbsG: 48, sodiumMg: 310, servingSize: "1 square (4×4 in)" },
    costing: { suggestedMenuPrice: 8 },
  },
];

export const BEVERAGE_RECIPES: Recipe[] = [
  {
    slug: "sweet-tea",
    name: "Sweet Tea",
    category: "Beverages",
    difficulty: "Easy",
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    holdTimeMinutes: 480,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Store in labeled cambro at 38°F. Refresh ice at service station each shift.",
    servingTemperature: "Cold — over ice, 41°F or below",
    internalTemps: [{ item: "Cold hold", tempF: 41 }],
    equipment: [...STANDARD_BEVERAGE_EQUIPMENT],
    description: "Southern sweet tea — black tea steeped strong, cut with cane sugar. PJ's serves it by the gallon.",
    image: menuImage("sweet-tea"),
    usageCount: 756,
    batchSizes: BEVERAGE_BATCH_SIZES,
    ingredients: [
      { name: "Black Tea Bags", amount: 32, unit: "ea", costPerUnit: 0.08 },
      { name: "Granulated Sugar", amount: 4, unit: "lb", costPerUnit: 0.06 },
      { name: "Water", amount: 8, unit: "gal", costPerUnit: 0 },
      { name: "Lemon Slices", amount: 16, unit: "ea", prepNotes: "Garnish", costPerUnit: 0.15 },
    ],
    steps: [
      "Bring 2 gal water to boil. Remove from heat.",
      "Steep tea bags 5 min — no longer or it turns bitter.",
      "Dissolve sugar in hot tea.",
      "Add remaining cold water. Chill to 38°F.",
    ],
    chefNotes: {
      tips: ["PJ's ratio: ½ cup sugar per gallon — adjust to taste.", "Never squeeze tea bags — releases tannins."],
      criticalControlPoints: ["Cold hold 41°F", "Label brew date"],
      commonMistakes: ["Oversteeping — bitter tea", "Adding sugar to cold tea — won't dissolve"],
      textureGuide: "Clean pour, no cloudiness.",
      colorGuide: "Deep amber, translucent.",
      tasteGuide: "Sweet first, tea tannins on finish — refreshing, not syrupy.",
    },
    nutrition: { calories: 90, proteinG: 0, fatG: 0, carbsG: 23, sodiumMg: 5, servingSize: "16 fl oz" },
    costing: { suggestedMenuPrice: 3.5 },
  },
  {
    slug: "unsweet-tea",
    name: "Unsweet Tea",
    category: "Beverages",
    difficulty: "Easy",
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    holdTimeMinutes: 480,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Same as sweet tea — separate labeled cambro.",
    servingTemperature: "Cold — over ice",
    internalTemps: [{ item: "Cold hold", tempF: 41 }],
    equipment: [...STANDARD_BEVERAGE_EQUIPMENT],
    description: "Unsweetened black tea for guests who want pure tea flavor. Offer simple syrup on the side.",
    image: menuImage("unsweet-tea"),
    usageCount: 412,
    batchSizes: BEVERAGE_BATCH_SIZES,
    ingredients: [
      { name: "Black Tea Bags", amount: 32, unit: "ea", costPerUnit: 0.08 },
      { name: "Water", amount: 8, unit: "gal", costPerUnit: 0 },
      { name: "Lemon Slices", amount: 16, unit: "ea", costPerUnit: 0.15 },
    ],
    steps: [
      "Steep 32 bags in 2 gal boiling water, 5 min.",
      "Remove bags. Add 6 gal cold water.",
      "Chill to 38°F. Serve over ice with lemon.",
    ],
    chefNotes: {
      tips: ["Keep simple syrup at station for optional sweetening.", "Same steep rules as sweet tea."],
      criticalControlPoints: ["Cold hold 41°F"],
      commonMistakes: ["Confusing cambros — label clearly"],
      textureGuide: "Clean, crisp pour.",
      colorGuide: "Light amber.",
      tasteGuide: "Bright tea flavor, zero sweetness.",
    },
    nutrition: { calories: 2, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 5, servingSize: "16 fl oz" },
    costing: { suggestedMenuPrice: 3.5 },
  },
  {
    slug: "lemonade",
    name: "Lemonade",
    category: "Beverages",
    difficulty: "Easy",
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    holdTimeMinutes: 480,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Store covered at 38°F. Stir before each pour — pulp settles.",
    servingTemperature: "Cold — over ice",
    internalTemps: [{ item: "Cold hold", tempF: 41 }],
    equipment: [...STANDARD_BEVERAGE_EQUIPMENT],
    description: "Fresh-squeezed style lemonade — tart, sweet, and bright. Made from concentrate base and fresh lemon.",
    image: menuImage("lemonade"),
    usageCount: 389,
    batchSizes: BEVERAGE_BATCH_SIZES,
    ingredients: [
      { name: "Lemon Juice", amount: 2, unit: "qt", prepNotes: "Fresh squeezed", costPerUnit: 0.35 },
      { name: "Granulated Sugar", amount: 3, unit: "lb", costPerUnit: 0.06 },
      { name: "Water", amount: 8, unit: "gal", costPerUnit: 0 },
      { name: "Lemon Wheels", amount: 24, unit: "ea", prepNotes: "Garnish", costPerUnit: 0.12 },
    ],
    steps: [
      "Dissolve sugar in 1 gal warm water.",
      "Add lemon juice and remaining cold water.",
      "Taste — should be tart-sweet balance.",
      "Chill and serve over ice with lemon wheel.",
    ],
    chefNotes: {
      tips: ["Roll lemons before juicing for max yield.", "Adjust sugar by ½ cup increments."],
      criticalControlPoints: ["Cold hold 41°F"],
      commonMistakes: ["Too sweet — masks lemon brightness"],
      textureGuide: "Light pulp acceptable.",
      colorGuide: "Cloudy pale yellow.",
      tasteGuide: "Bright acid, clean sweetness.",
    },
    nutrition: { calories: 110, proteinG: 0, fatG: 0, carbsG: 28, sodiumMg: 8, servingSize: "16 fl oz" },
    costing: { suggestedMenuPrice: 4 },
  },
  {
    slug: "strawberry-lemonade",
    name: "Strawberry Lemonade",
    category: "Beverages",
    difficulty: "Easy",
    prepTimeMinutes: 25,
    cookTimeMinutes: 0,
    holdTimeMinutes: 480,
    shelfLife: "2 days refrigerated — fresh berry batch",
    storageInstructions: "Store at 38°F. Berry puree separates — stir or shake before service.",
    servingTemperature: "Cold — over ice",
    internalTemps: [{ item: "Cold hold", tempF: 41 }],
    equipment: [...STANDARD_BEVERAGE_EQUIPMENT],
    description: "House lemonade blended with fresh strawberry puree — summer in a cup.",
    image: menuImage("strawberry-lemonade"),
    usageCount: 298,
    batchSizes: BEVERAGE_BATCH_SIZES,
    ingredients: [
      { name: "Lemon Juice", amount: 1.5, unit: "qt", costPerUnit: 0.35 },
      { name: "Fresh Strawberries", amount: 6, unit: "lb", prepNotes: "Hulled, pureed", costPerUnit: 2.8 },
      { name: "Granulated Sugar", amount: 3.5, unit: "lb", costPerUnit: 0.06 },
      { name: "Water", amount: 8, unit: "gal", costPerUnit: 0 },
      { name: "Strawberry Slices", amount: 32, unit: "ea", prepNotes: "Garnish", costPerUnit: 0.1 },
    ],
    steps: [
      "Puree strawberries with 1 cup sugar.",
      "Make lemonade base with remaining sugar, lemon, and water.",
      "Whisk in strawberry puree. Strain if smoother texture desired.",
      "Chill and garnish with strawberry slice.",
    ],
    chefNotes: {
      tips: ["Use ripe berries — underripe = tart and pale.", "Strain for clearer service, skip for rustic."],
      criticalControlPoints: ["Cold hold 41°F", "Use within 2 days — berries degrade"],
      commonMistakes: ["Seeds in puree — use fine mesh if needed"],
      textureGuide: "Silky with light berry pulp.",
      colorGuide: "Blush pink, not neon red.",
      tasteGuide: "Strawberry forward, lemon brightness on finish.",
    },
    nutrition: { calories: 130, proteinG: 0, fatG: 0, carbsG: 32, sodiumMg: 8, servingSize: "16 fl oz" },
    costing: { suggestedMenuPrice: 4.5 },
  },
];
