import { menuImage } from "@/lib/content/menu";
import { GUMBO_BATCH_SIZES } from "./batches";
import { STANDARD_GUMBO_EQUIPMENT } from "./equipment";
import type { ChefNotes, Recipe, RecipeIngredient } from "./types";

const GUMBO_INTERNAL_TEMPS = [
  { item: "Chicken thigh (shredded)", tempF: 165, note: "Hold above 140°F in hot well" },
  { item: "Smoked sausage", tempF: 165 },
  { item: "Gulf shrimp", tempF: 145, note: "Add at finish — do not boil" },
  { item: "Finished gumbo (service)", tempF: 165, note: "Minimum hot-hold temperature" },
];

const GUMBO_CHEF_NOTES: ChefNotes = {
  tips: [
    "Stir roux constantly — burnt roux cannot be saved.",
    "Add okra in two stages: half in the trinity sweat, half at simmer for texture contrast.",
    "Rest finished gumbo 20 minutes off heat before service; flavors marry.",
    "Taste after every protein addition — salt needs shift as volume grows.",
  ],
  criticalControlPoints: [
    "Roux color must reach dark chocolate before adding trinity.",
    "Maintain simmer below a rolling boil once stock is added.",
    "Hot-hold at 165°F minimum; discard after 4-hour hold window.",
    "Cool from 135°F to 70°F within 2 hours for refrigeration.",
  ],
  commonMistakes: [
    "Rushing the roux — pale roux equals thin flavor.",
    "Boiling shrimp or crab — proteins turn rubbery and cloud the pot.",
    "Under-seasoning at the finish — gumbo should taste bold before rice.",
    "Adding cold stock to hot roux — always warm stock to prevent seizing.",
  ],
  textureGuide:
    "Silky, spoon-coating body with tender okra and shredded chicken. Sausage slices hold their snap. Not stew-thick, not broth-thin.",
  colorGuide:
    "Deep mahogany brown with amber highlights. Oil sheen on surface is normal — skim excess before service if needed.",
  tasteGuide:
    "Savory, layered, and round. Roux depth first, then trinity sweetness, then smoked meat and seafood on the finish. Mild builds warmth; spicy adds bright serrano heat without masking the roux.",
};

function gumboBase(
  slug: string,
  name: string,
  description: string,
  ingredients: RecipeIngredient[],
  steps: string[],
  overrides: Partial<Recipe> = {},
): Recipe {
  return {
    slug,
    name,
    category: "Gumbo",
    difficulty: "Advanced",
    prepTimeMinutes: 90,
    cookTimeMinutes: 180,
    holdTimeMinutes: 240,
    shelfLife: "4 days refrigerated; 3 months frozen",
    storageInstructions:
      "Cool in shallow hotel pans with ice paddle. Label with date, batch size, and protein type. Store covered at 38°F or below.",
    servingTemperature: "165°F minimum — ladled over steamed white rice",
    internalTemps: GUMBO_INTERNAL_TEMPS,
    equipment: [...STANDARD_GUMBO_EQUIPMENT],
    description,
    image: menuImage(slug),
    usageCount: 0,
    batchSizes: GUMBO_BATCH_SIZES,
    ingredients,
    steps,
    chefNotes: GUMBO_CHEF_NOTES,
    nutrition: {
      calories: 420,
      proteinG: 28,
      fatG: 22,
      carbsG: 24,
      sodiumMg: 980,
      servingSize: "12 oz gumbo + 4 oz rice",
    },
    costing: { suggestedMenuPrice: 16 },
    ...overrides,
  };
}

const signatureIngredients: RecipeIngredient[] = [
  { name: "Chicken Thigh", amount: 15, unit: "lb", prepNotes: "Boneless, skinless", costPerUnit: 1.89 },
  { name: "Smoked Andouille Sausage", amount: 8, unit: "lb", prepNotes: "Bias-cut ¼ in", costPerUnit: 3.49 },
  { name: "Gulf Shrimp (21/25)", amount: 6, unit: "lb", prepNotes: "Peeled, deveined", costPerUnit: 7.95 },
  { name: "Yellow Onion", amount: 6, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
  { name: "Green Bell Pepper", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
  { name: "Celery", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
  { name: "Garlic", amount: 10, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
  { name: "Fresh Okra", amount: 4, unit: "lb", prepNotes: "Trimmed, halved", costPerUnit: 2.25 },
  { name: "Vegetable Oil", amount: 4, unit: "qt", costPerUnit: 1.8 },
  { name: "All-Purpose Flour", amount: 4, unit: "qt", prepNotes: "For dark roux", costPerUnit: 0.11 },
  { name: "Chicken Stock", amount: 10, unit: "gal", prepNotes: "Warm", costPerUnit: 0.45 },
  { name: "Kosher Salt", amount: 6, unit: "oz", costPerUnit: 0.08 },
  { name: "Black Pepper", amount: 2, unit: "oz", costPerUnit: 0.42 },
  { name: "Paprika", amount: 3, unit: "oz", costPerUnit: 0.38 },
  { name: "Garlic Powder", amount: 2, unit: "oz", costPerUnit: 0.35 },
  { name: "Onion Powder", amount: 2, unit: "oz", costPerUnit: 0.32 },
  { name: "Cajun Seasoning", amount: 8, unit: "oz", costPerUnit: 0.27 },
  { name: "Worcestershire Sauce", amount: 2, unit: "cups", costPerUnit: 0.15 },
  { name: "Bay Leaves", amount: 12, unit: "ea", costPerUnit: 0.05 },
  { name: "Fresh Thyme", amount: 1, unit: "bunch", prepNotes: "Tied", costPerUnit: 2.5 },
  { name: "Flat-Leaf Parsley", amount: 8, unit: "oz", prepNotes: "Chopped for finish", costPerUnit: 0.4 },
  { name: "Green Onion", amount: 2, unit: "bunch", prepNotes: "Sliced for garnish", costPerUnit: 1.2 },
  { name: "Serrano Peppers", amount: 8, unit: "oz", prepNotes: "Spicy version — minced", costPerUnit: 2.4 },
];

const signatureSteps = [
  "Mise en place: dice holy trinity, mince garlic, trim chicken, slice sausage, peel shrimp, prep okra.",
  "Warm chicken stock in 40 qt pot — keep at a simmer.",
  "Make dark roux: heat oil in 80 qt steam kettle over medium. Whisk in flour. Stir constantly 45–60 min until color of dark chocolate.",
  "Add trinity to roux. Sweat 12–15 min until onions are translucent and edges caramelize.",
  "Add garlic and half the okra. Cook 5 min.",
  "Deglaze with 2 qt warm stock, scraping fond.",
  "Whisk in remaining stock in stages. Add bay leaves and thyme bundle.",
  "Simmer uncovered 90 min, skimming as needed. Body should coat the back of a spoon.",
  "Season with salt, pepper, paprika, garlic powder, onion powder, Cajun seasoning, and Worcestershire.",
  "Shred chicken and return to pot with sausage. Simmer 20 min.",
  "Add remaining okra and shrimp. Cook 8 min — shrimp opaque, curled.",
  "Finish with parsley and green onion. Taste and adjust.",
  "Hold at 165°F or cool for storage per HACCP.",
  "Serve over steamed white rice. Garnish with green onion.",
];

export const GUMBO_RECIPES: Recipe[] = [
  gumboBase(
    "pjs-signature-gumbo",
    "PJ's Signature Gumbo",
    "The house pot — dark hand-stirred roux, holy trinity, chicken, smoked andouille, Gulf shrimp, and okra. This is the recipe every shift lead knows by heart.",
    signatureIngredients,
    signatureSteps,
    { usageCount: 842, costing: { suggestedMenuPrice: 16 } },
  ),
  gumboBase(
    "chicken-sausage-gumbo",
    "Chicken & Sausage Gumbo",
    "Louisiana classic without seafood. Built on the same mahogany roux with chicken thigh and smoked andouille — the weekday workhorse batch.",
    [
      { name: "Chicken Thigh", amount: 18, unit: "lb", prepNotes: "Boneless, skinless", costPerUnit: 1.89 },
      { name: "Smoked Andouille Sausage", amount: 10, unit: "lb", prepNotes: "Bias-cut ¼ in", costPerUnit: 3.49 },
      { name: "Yellow Onion", amount: 6, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Green Bell Pepper", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
      { name: "Celery", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
      { name: "Garlic", amount: 10, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Vegetable Oil", amount: 4, unit: "qt", costPerUnit: 1.8 },
      { name: "All-Purpose Flour", amount: 4, unit: "qt", costPerUnit: 0.11 },
      { name: "Chicken Stock", amount: 10, unit: "gal", prepNotes: "Warm", costPerUnit: 0.45 },
      { name: "Kosher Salt", amount: 5, unit: "oz", costPerUnit: 0.08 },
      { name: "Black Pepper", amount: 2, unit: "oz", costPerUnit: 0.42 },
      { name: "Cajun Seasoning", amount: 6, unit: "oz", costPerUnit: 0.27 },
      { name: "Worcestershire Sauce", amount: 1.5, unit: "cups", costPerUnit: 0.15 },
      { name: "Bay Leaves", amount: 10, unit: "ea", costPerUnit: 0.05 },
      { name: "Fresh Thyme", amount: 1, unit: "bunch", costPerUnit: 2.5 },
      { name: "Green Onion", amount: 2, unit: "bunch", prepNotes: "Garnish", costPerUnit: 1.2 },
      { name: "Serrano Peppers", amount: 6, unit: "oz", prepNotes: "Spicy version", costPerUnit: 2.4 },
    ],
    [
      "Prep all vegetables and proteins.",
      "Warm stock. Begin dark roux in steam kettle.",
      "Sweat trinity in roux 12 min. Add garlic.",
      "Deglaze and add stock with herbs.",
      "Simmer 90 min. Season to taste.",
      "Add shredded chicken and sausage. Simmer 25 min.",
      "Finish with green onion. Taste and adjust.",
      "Hold hot or cool per HACCP.",
    ],
    { usageCount: 615, costing: { suggestedMenuPrice: 14 } },
  ),
  gumboBase(
    "chicken-gumbo",
    "Chicken Gumbo",
    "All-chicken comfort — no sausage, no seafood. Same deep roux foundation with extra thigh meat for a clean, rich bowl.",
    [
      { name: "Chicken Thigh", amount: 22, unit: "lb", prepNotes: "Boneless, skinless", costPerUnit: 1.89 },
      { name: "Yellow Onion", amount: 5, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Green Bell Pepper", amount: 2.5, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
      { name: "Celery", amount: 2.5, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
      { name: "Garlic", amount: 8, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Vegetable Oil", amount: 3.5, unit: "qt", costPerUnit: 1.8 },
      { name: "All-Purpose Flour", amount: 3.5, unit: "qt", costPerUnit: 0.11 },
      { name: "Chicken Stock", amount: 10, unit: "gal", costPerUnit: 0.45 },
      { name: "Kosher Salt", amount: 5, unit: "oz", costPerUnit: 0.08 },
      { name: "Black Pepper", amount: 1.5, unit: "oz", costPerUnit: 0.42 },
      { name: "Cajun Seasoning", amount: 5, unit: "oz", costPerUnit: 0.27 },
      { name: "Bay Leaves", amount: 8, unit: "ea", costPerUnit: 0.05 },
      { name: "Green Onion", amount: 2, unit: "bunch", costPerUnit: 1.2 },
    ],
    [
      "Season and sear half the chicken. Reserve.",
      "Build dark roux. Sweat trinity.",
      "Add stock and remaining chicken. Simmer until shreddable.",
      "Shred chicken back into pot. Season and finish.",
    ],
    {
      difficulty: "Intermediate",
      usageCount: 388,
      costing: { suggestedMenuPrice: 13 },
      nutrition: { calories: 380, proteinG: 32, fatG: 18, carbsG: 20, sodiumMg: 920, servingSize: "12 oz gumbo + 4 oz rice" },
    },
  ),
  gumboBase(
    "veggie-gumbo",
    "Veggie Gumbo",
    "Plant-forward but still roux-built. Okra, trinity, tomatoes, and vegetable stock — no meat, all soul.",
    [
      { name: "Yellow Onion", amount: 6, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Green Bell Pepper", amount: 4, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
      { name: "Celery", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
      { name: "Fresh Okra", amount: 6, unit: "lb", prepNotes: "Halved", costPerUnit: 2.25 },
      { name: "Garlic", amount: 10, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Crushed Tomatoes", amount: 2, unit: "qt", costPerUnit: 0.55 },
      { name: "Vegetable Oil", amount: 3, unit: "qt", costPerUnit: 1.8 },
      { name: "All-Purpose Flour", amount: 3, unit: "qt", costPerUnit: 0.11 },
      { name: "Vegetable Stock", amount: 10, unit: "gal", costPerUnit: 0.38 },
      { name: "Kosher Salt", amount: 4, unit: "oz", costPerUnit: 0.08 },
      { name: "Cajun Seasoning", amount: 6, unit: "oz", costPerUnit: 0.27 },
      { name: "Bay Leaves", amount: 8, unit: "ea", costPerUnit: 0.05 },
      { name: "Green Onion", amount: 2, unit: "bunch", costPerUnit: 1.2 },
    ],
    [
      "Roast half the okra on sheet pan at 425°F for 15 min — reduces slime.",
      "Build dark roux. Sweat trinity and remaining okra.",
      "Add tomatoes, then vegetable stock.",
      "Simmer 75 min. Finish with green onion.",
    ],
    {
      difficulty: "Intermediate",
      usageCount: 201,
      costing: { suggestedMenuPrice: 13 },
      internalTemps: [{ item: "Finished gumbo (service)", tempF: 165 }],
      nutrition: { calories: 290, proteinG: 6, fatG: 14, carbsG: 34, sodiumMg: 840, servingSize: "12 oz gumbo + 4 oz rice" },
    },
  ),
  gumboBase(
    "blue-crab-sausage-gumbo",
    "Weekend Blue Crab & Sausage Gumbo",
    "Weekend luxury batch — sweet Gulf blue crab and smoked sausage in a seafood-forward roux. Saturday and Sunday only.",
    [
      { name: "Blue Crab Meat", amount: 8, unit: "lb", prepNotes: "Picked, shell-free", costPerUnit: 9.5 },
      { name: "Smoked Andouille Sausage", amount: 8, unit: "lb", prepNotes: "Bias-cut", costPerUnit: 3.49 },
      { name: "Yellow Onion", amount: 5, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Green Bell Pepper", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
      { name: "Celery", amount: 3, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
      { name: "Garlic", amount: 10, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Vegetable Oil", amount: 4, unit: "qt", costPerUnit: 1.8 },
      { name: "All-Purpose Flour", amount: 4, unit: "qt", costPerUnit: 0.11 },
      { name: "Seafood Stock", amount: 10, unit: "gal", prepNotes: "Warm", costPerUnit: 0.52 },
      { name: "Kosher Salt", amount: 4, unit: "oz", costPerUnit: 0.08 },
      { name: "Cajun Seasoning", amount: 6, unit: "oz", costPerUnit: 0.27 },
      { name: "Old Bay", amount: 3, unit: "oz", costPerUnit: 0.45 },
      { name: "Bay Leaves", amount: 10, unit: "ea", costPerUnit: 0.05 },
      { name: "Green Onion", amount: 3, unit: "bunch", costPerUnit: 1.2 },
    ],
    [
      "Inspect crab for shell — pick twice.",
      "Build dark roux with seafood stock base.",
      "Simmer sausage 30 min before adding crab.",
      "Fold crab in gently at finish — 5 min max.",
      "Never boil after crab is added.",
    ],
    {
      difficulty: "Expert",
      usageCount: 156,
      costing: { suggestedMenuPrice: 19 },
      internalTemps: [
        { item: "Smoked sausage", tempF: 165 },
        { item: "Blue crab (added at finish)", tempF: 145, note: "Gentle heat only" },
      ],
      nutrition: { calories: 450, proteinG: 26, fatG: 24, carbsG: 22, sodiumMg: 1100, servingSize: "12 oz gumbo + 4 oz rice" },
    },
  ),
];
