import { menuImage } from "@/lib/content/menu";
import { SIDE_BATCH_SIZES, BREAD_BATCH_SIZES } from "./batches";
import { STANDARD_BREAD_EQUIPMENT, STANDARD_SIDE_EQUIPMENT } from "./equipment";
import type { Recipe } from "./types";

export const SIDE_RECIPES: Recipe[] = [
  {
    slug: "cornbread-muffins",
    name: "Cornbread Muffins",
    category: "Breads",
    difficulty: "Easy",
    prepTimeMinutes: 15,
    cookTimeMinutes: 18,
    holdTimeMinutes: 120,
    shelfLife: "2 days at room temp; 5 days refrigerated",
    storageInstructions: "Cool on rack. Store in airtight cambro at room temp for service day. Do not refrigerate unless holding overnight.",
    servingTemperature: "Warm — 140°F minimum if held",
    internalTemps: [{ item: "Muffin center", tempF: 200, note: "Bake until toothpick clean" }],
    equipment: [...STANDARD_BREAD_EQUIPMENT],
    description: "Golden Southern cornbread muffins — slightly sweet, crisp edges, tender crumb. Baked fresh every morning shift.",
    image: menuImage("cornbread-muffins"),
    usageCount: 534,
    batchSizes: BREAD_BATCH_SIZES,
    ingredients: [
      { name: "Cornbread Mix", amount: 8, unit: "lb", costPerUnit: 0.9 },
      { name: "Eggs", amount: 24, unit: "ea", costPerUnit: 0.22 },
      { name: "Whole Milk", amount: 2, unit: "qt", costPerUnit: 0.18 },
      { name: "Vegetable Oil", amount: 2, unit: "cups", costPerUnit: 0.04 },
      { name: "Granulated Sugar", amount: 8, unit: "oz", costPerUnit: 0.06 },
      { name: "Kosher Salt", amount: 1, unit: "oz", costPerUnit: 0.08 },
    ],
    steps: [
      "Preheat convection oven to 375°F.",
      "Whisk eggs, milk, oil, and sugar until combined.",
      "Fold in cornbread mix and salt — do not overmix.",
      "Portion into greased muffin tins, ¾ full.",
      "Bake 16–18 min until golden and springy.",
      "Cool 5 min in tin, then transfer to rack.",
    ],
    chefNotes: {
      tips: ["Rest batter 5 min before baking for taller domes.", "Brush tops with melted butter out of oven."],
      criticalControlPoints: ["Internal temp 200°F+", "Hold covered — dry out if exposed"],
      commonMistakes: ["Overmixing — tough muffins", "Underbaking — gummy center"],
      textureGuide: "Tender crumb with crisp golden cap and slight mealiness from corn.",
      colorGuide: "Deep golden brown top, pale yellow interior.",
      tasteGuide: "Lightly sweet, buttery corn flavor — pairs with spicy gumbo.",
    },
    nutrition: { calories: 210, proteinG: 4, fatG: 9, carbsG: 28, sodiumMg: 380, servingSize: "1 muffin" },
    costing: { suggestedMenuPrice: 5 },
  },
  {
    slug: "jalapeno-cheddar-cornbread-muffins",
    name: "Jalapeño Cheddar Cornbread Muffins",
    category: "Breads",
    difficulty: "Easy",
    prepTimeMinutes: 20,
    cookTimeMinutes: 18,
    holdTimeMinutes: 120,
    shelfLife: "2 days at room temp",
    storageInstructions: "Same as standard cornbread — label spicy for allergen awareness.",
    servingTemperature: "Warm — 140°F minimum if held",
    internalTemps: [{ item: "Muffin center", tempF: 200 }],
    equipment: [...STANDARD_BREAD_EQUIPMENT],
    description: "Cornbread muffins loaded with shredded cheddar and diced jalapeño — heat and cheese in every bite.",
    image: menuImage("jalapeno-cheddar-cornbread-muffins"),
    usageCount: 412,
    batchSizes: BREAD_BATCH_SIZES,
    ingredients: [
      { name: "Cornbread Mix", amount: 8, unit: "lb", costPerUnit: 0.9 },
      { name: "Eggs", amount: 24, unit: "ea", costPerUnit: 0.22 },
      { name: "Whole Milk", amount: 2, unit: "qt", costPerUnit: 0.18 },
      { name: "Vegetable Oil", amount: 2, unit: "cups", costPerUnit: 0.04 },
      { name: "Shredded Cheddar", amount: 3, unit: "lb", prepNotes: "Fine shred", costPerUnit: 3.1 },
      { name: "Jalapeños", amount: 1.5, unit: "lb", prepNotes: "Seeded, small dice", costPerUnit: 1.6 },
      { name: "Kosher Salt", amount: 1, unit: "oz", costPerUnit: 0.08 },
    ],
    steps: [
      "Toss jalapeño and cheddar with 2 tbsp mix to prevent sinking.",
      "Mix wet ingredients and remaining dry.",
      "Fold in cheese and jalapeño.",
      "Bake 375°F, 16–18 min.",
    ],
    chefNotes: {
      tips: ["Wear gloves when seeding jalapeños.", "Reserve cheese for tops last 2 min for visual appeal."],
      criticalControlPoints: ["Label as contains dairy", "Monitor jalapeño heat batch to batch"],
      commonMistakes: ["Jalapeño pools at bottom — coat in flour first", "Too much cheese — greasy muffins"],
      textureGuide: "Same tender crumb as standard with melted cheese pockets.",
      colorGuide: "Golden with green jalapeño flecks and orange cheese.",
      tasteGuide: "Corn sweetness, sharp cheddar, building jalapeño heat.",
    },
    nutrition: { calories: 265, proteinG: 8, fatG: 14, carbsG: 26, sodiumMg: 420, servingSize: "1 muffin" },
    costing: { suggestedMenuPrice: 6 },
  },
  {
    slug: "french-fries",
    name: "French Fries",
    category: "Sides",
    difficulty: "Intermediate",
    prepTimeMinutes: 30,
    cookTimeMinutes: 12,
    holdTimeMinutes: 7,
    shelfLife: "Serve immediately — 7 min max hold",
    storageInstructions: "Blanched fries: drain, cool, store in freezer bags. Finished fries: do not hold.",
    servingTemperature: "Hot — 165°F minimum",
    internalTemps: [{ item: "Fry oil", tempF: 350, note: "Maintain 340–360°F" }],
    equipment: [...STANDARD_SIDE_EQUIPMENT],
    description: "Double-fried russet fries — crisp exterior, fluffy interior, dusted with Cajun seasoning.",
    image: menuImage("french-fries"),
    usageCount: 298,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Russet Potatoes", amount: 25, unit: "lb", prepNotes: "Hand-cut ⅜ in", costPerUnit: 0.55 },
      { name: "Fry Oil", amount: 4, unit: "gal", costPerUnit: 1.8 },
      { name: "Kosher Salt", amount: 4, unit: "oz", costPerUnit: 0.08 },
      { name: "Cajun Seasoning", amount: 3, unit: "oz", costPerUnit: 0.27 },
    ],
    steps: [
      "Cut potatoes, rinse until water runs clear. Soak 30 min.",
      "Blanch at 325°F, 4 min. Drain and cool completely.",
      "Finish fry at 350°F, 3–4 min until golden.",
      "Toss with salt and Cajun seasoning. Serve immediately.",
    ],
    chefNotes: {
      tips: ["Double fry is non-negotiable for crispness.", "Season while hot — salt sticks better."],
      criticalControlPoints: ["Oil temp 340–360°F", "7-minute hold max"],
      commonMistakes: ["Skipping soak — starch makes fries soggy", "Crowding fryer — drops oil temp"],
      textureGuide: "Shattering crisp shell, steamy fluffy center.",
      colorGuide: "Even golden with light Cajun speckle.",
      tasteGuide: "Potato-forward, salty, warm spice on finish.",
    },
    nutrition: { calories: 320, proteinG: 4, fatG: 16, carbsG: 42, sodiumMg: 520, servingSize: "5 oz portion" },
    costing: { suggestedMenuPrice: 5 },
  },
  {
    slug: "cole-slaw",
    name: "Cole Slaw",
    category: "Sides",
    difficulty: "Easy",
    prepTimeMinutes: 25,
    cookTimeMinutes: 0,
    holdTimeMinutes: 480,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Store covered at 38°F. Drain excess liquid before service if needed.",
    servingTemperature: "Cold — 41°F or below",
    internalTemps: [{ item: "Storage", tempF: 41, note: "Cold hold maximum" }],
    equipment: [...STANDARD_SIDE_EQUIPMENT],
    description: "Creamy-tangy slaw with green and red cabbage, carrots, and buttermilk dressing. Cut fine for sandwich and side service.",
    image: menuImage("cole-slaw"),
    usageCount: 267,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Green Cabbage", amount: 8, unit: "lb", prepNotes: "Shredded fine", costPerUnit: 0.72 },
      { name: "Red Cabbage", amount: 2, unit: "lb", prepNotes: "Shredded fine", costPerUnit: 0.85 },
      { name: "Carrots", amount: 2, unit: "lb", prepNotes: "Julienned", costPerUnit: 0.65 },
      { name: "Mayonnaise", amount: 2, unit: "qt", costPerUnit: 0.12 },
      { name: "Buttermilk", amount: 1, unit: "qt", costPerUnit: 0.2 },
      { name: "Apple Cider Vinegar", amount: 8, unit: "oz", costPerUnit: 0.08 },
      { name: "Granulated Sugar", amount: 6, unit: "oz", costPerUnit: 0.06 },
      { name: "Kosher Salt", amount: 2, unit: "oz", costPerUnit: 0.08 },
      { name: "Black Pepper", amount: 1, unit: "oz", costPerUnit: 0.42 },
    ],
    steps: [
      "Shred cabbages and carrots. Salt lightly, rest 10 min, drain.",
      "Whisk mayo, buttermilk, vinegar, sugar, salt, and pepper.",
      "Toss dressing with slaw. Rest 30 min before service.",
    ],
    chefNotes: {
      tips: ["Salt-and-drain cabbage prevents watery slaw.", "Add dressing in two stages for even coat."],
      criticalControlPoints: ["Cold hold 41°F", "Use within 3 days"],
      commonMistakes: ["Dressing too early for large batches — cabbage weeps"],
      textureGuide: "Fine shred, creamy cling, still crunchy.",
      colorGuide: "Purple-green mix with orange carrot threads.",
      tasteGuide: "Tangy, slightly sweet, peppery finish.",
    },
    nutrition: { calories: 145, proteinG: 1, fatG: 11, carbsG: 11, sodiumMg: 280, servingSize: "4 oz portion" },
    costing: { suggestedMenuPrice: 4.5 },
  },
  {
    slug: "dirty-rice",
    name: "Dirty Rice",
    category: "Sides",
    difficulty: "Intermediate",
    prepTimeMinutes: 35,
    cookTimeMinutes: 25,
    holdTimeMinutes: 120,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Hold in hotel pan covered at 140°F+. Cool rapidly if storing.",
    servingTemperature: "Hot — 165°F minimum",
    internalTemps: [{ item: "Chicken liver", tempF: 165 }, { item: "Service hold", tempF: 140 }],
    equipment: [...STANDARD_SIDE_EQUIPMENT],
    description: "Cajun dirty rice with ground chicken liver, andouille, trinity, and long-grain rice — deeply savory side.",
    image: menuImage("dirty-rice"),
    usageCount: 189,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Long Grain White Rice", amount: 6, unit: "lb", costPerUnit: 0.62 },
      { name: "Chicken Livers", amount: 3, unit: "lb", prepNotes: "Ground fine", costPerUnit: 2.1 },
      { name: "Ground Pork", amount: 2, unit: "lb", costPerUnit: 2.8 },
      { name: "Smoked Andouille", amount: 2, unit: "lb", prepNotes: "Small dice", costPerUnit: 3.49 },
      { name: "Yellow Onion", amount: 2, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Green Bell Pepper", amount: 1, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.15 },
      { name: "Celery", amount: 1, unit: "lb", prepNotes: "Small dice", costPerUnit: 1.05 },
      { name: "Garlic", amount: 4, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Chicken Stock", amount: 3, unit: "gal", costPerUnit: 0.45 },
      { name: "Cajun Seasoning", amount: 4, unit: "oz", costPerUnit: 0.27 },
      { name: "Green Onion", amount: 1, unit: "bunch", costPerUnit: 1.2 },
    ],
    steps: [
      "Render andouille. Remove, reserve fat.",
      "Brown liver and pork in same pot. Break up fine.",
      "Sweat trinity in reserved fat.",
      "Add rice, toast 2 min. Add stock and seasoning.",
      "Simmer covered 18 min. Rest 10 min, fluff with fork.",
      "Fold in andouille and green onion.",
    ],
    chefNotes: {
      tips: ["Grind livers twice for smooth texture.", "Do not stir rice during simmer — breaks grains."],
      criticalControlPoints: ["Liver cooked to 165°F", "Hot hold 140°F+"],
      commonMistakes: ["Mushy rice from over-stirring", "Liver chunks too large — gritty texture"],
      textureGuide: "Separate rice grains coated in savory mix, not clumped.",
      colorGuide: "Speckled brown from liver and andouille.",
      tasteGuide: "Earthy, rich, peppery — umami from liver without iron-heavy aftertaste.",
    },
    nutrition: { calories: 310, proteinG: 14, fatG: 12, carbsG: 38, sodiumMg: 720, servingSize: "6 oz portion" },
    costing: { suggestedMenuPrice: 6 },
  },
  {
    slug: "fried-okra",
    name: "Fried Okra",
    category: "Sides",
    difficulty: "Intermediate",
    prepTimeMinutes: 20,
    cookTimeMinutes: 8,
    holdTimeMinutes: 10,
    shelfLife: "Serve same shift — texture degrades quickly",
    storageInstructions: "Prep dredged okra in hotel pan with parchment between layers. Fry to order when possible.",
    servingTemperature: "Hot — 165°F minimum",
    internalTemps: [{ item: "Fry oil", tempF: 375 }],
    equipment: [...STANDARD_SIDE_EQUIPMENT],
    description: "Cornmeal-crusted okra, fried until crisp with a tender center. A Louisiana staple.",
    image: menuImage("fried-okra"),
    usageCount: 178,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Fresh Okra", amount: 12, unit: "lb", prepNotes: "Trimmed, halved lengthwise", costPerUnit: 2.25 },
      { name: "Cornmeal", amount: 3, unit: "lb", costPerUnit: 0.55 },
      { name: "All-Purpose Flour", amount: 1.5, unit: "lb", costPerUnit: 0.45 },
      { name: "Cajun Seasoning", amount: 4, unit: "oz", costPerUnit: 0.27 },
      { name: "Buttermilk", amount: 2, unit: "qt", costPerUnit: 0.2 },
      { name: "Kosher Salt", amount: 2, unit: "oz", costPerUnit: 0.08 },
      { name: "Fry Oil", amount: 3, unit: "gal", costPerUnit: 1.8 },
    ],
    steps: [
      "Toss okra with salt, rest 10 min.",
      "Mix cornmeal, flour, and Cajun seasoning.",
      "Dip okra in buttermilk, dredge in cornmeal mix.",
      "Fry at 375°F in batches until deep golden, 3–4 min.",
      "Drain on rack, season immediately.",
    ],
    chefNotes: {
      tips: ["Do not overcrowd — steam prevents crisping.", "Serve with ranch or comeback sauce."],
      criticalControlPoints: ["Oil 375°F", "10-minute hold max"],
      commonMistakes: ["Wet okra — breading falls off", "Underseasoned dredge"],
      textureGuide: "Shatter-crisp coating, tender okra inside.",
      colorGuide: "Deep golden cornmeal crust.",
      tasteGuide: "Corn crunch, okra vegetal sweetness, Cajun spice.",
    },
    nutrition: { calories: 280, proteinG: 4, fatG: 14, carbsG: 34, sodiumMg: 480, servingSize: "5 oz portion" },
    costing: { suggestedMenuPrice: 6 },
  },
  {
    slug: "cajun-green-beans",
    name: "Cajun Green Beans",
    category: "Sides",
    difficulty: "Easy",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    holdTimeMinutes: 120,
    shelfLife: "3 days refrigerated",
    storageInstructions: "Hold in hotel pan at 140°F+. Label with date.",
    servingTemperature: "Hot — 165°F minimum",
    internalTemps: [{ item: "Service hold", tempF: 140 }],
    equipment: [...STANDARD_SIDE_EQUIPMENT],
    description: "Smothered green beans with trinity, smoked ham hock, and Cajun spice — low and slow Southern style.",
    image: menuImage("cajun-green-beans"),
    usageCount: 145,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Fresh Green Beans", amount: 12, unit: "lb", prepNotes: "Trimmed", costPerUnit: 1.85 },
      { name: "Smoked Ham Hock", amount: 4, unit: "lb", costPerUnit: 2.4 },
      { name: "Yellow Onion", amount: 2, unit: "lb", prepNotes: "Small dice", costPerUnit: 0.69 },
      { name: "Garlic", amount: 4, unit: "oz", prepNotes: "Minced", costPerUnit: 0.35 },
      { name: "Chicken Stock", amount: 2, unit: "gal", costPerUnit: 0.45 },
      { name: "Cajun Seasoning", amount: 3, unit: "oz", costPerUnit: 0.27 },
      { name: "Kosher Salt", amount: 2, unit: "oz", costPerUnit: 0.08 },
      { name: "Black Pepper", amount: 1, unit: "oz", costPerUnit: 0.42 },
    ],
    steps: [
      "Simmer ham hock in stock 45 min until meat pulls.",
      "Add trinity and garlic, sweat 8 min.",
      "Add green beans and seasoning. Simmer 25 min until tender but not mush.",
      "Pull meat from hock, fold back in.",
    ],
    chefNotes: {
      tips: ["Ham hock adds body — skim excess fat if needed.", "Beans should bend, not snap."],
      criticalControlPoints: ["Hot hold 140°F+", "Ham fully cooked"],
      commonMistakes: ["Overcooked beans — army green and mushy"],
      textureGuide: "Tender with slight bite, silky pot liquor.",
      colorGuide: "Deep green beans in amber broth.",
      tasteGuide: "Smoky ham, trinity sweetness, peppery Cajun finish.",
    },
    nutrition: { calories: 95, proteinG: 6, fatG: 3, carbsG: 12, sodiumMg: 640, servingSize: "5 oz portion" },
    costing: { suggestedMenuPrice: 5 },
  },
  {
    slug: "white-rice",
    name: "White Rice",
    category: "Sides",
    difficulty: "Easy",
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    holdTimeMinutes: 240,
    shelfLife: "Same day ideal; 2 days refrigerated",
    storageInstructions: "Hold in rice cooker on warm (140°F+). Fluff before each service. Never leave at room temp.",
    servingTemperature: "Hot — 140°F minimum",
    internalTemps: [{ item: "Service hold", tempF: 140 }],
    equipment: ["Rice Cooker", "40 qt Stock Pot", "Hotel Pans", "Ladle", "Measuring Cups", "Scale"],
    description: "Fluffy long-grain white rice — the foundation under every bowl of gumbo.",
    image: menuImage("white-rice"),
    usageCount: 891,
    batchSizes: SIDE_BATCH_SIZES,
    ingredients: [
      { name: "Long Grain White Rice", amount: 8, unit: "lb", costPerUnit: 0.62 },
      { name: "Water", amount: 4, unit: "gal", costPerUnit: 0 },
      { name: "Kosher Salt", amount: 3, unit: "oz", costPerUnit: 0.08 },
      { name: "Vegetable Oil", amount: 4, unit: "oz", costPerUnit: 0.04 },
    ],
    steps: [
      "Rinse rice until water runs mostly clear.",
      "Combine rice, water, salt, and oil in rice cooker.",
      "Cook on standard cycle. Rest 10 min with lid on.",
      "Fluff with fork. Hold on warm.",
    ],
    chefNotes: {
      tips: ["1:1.75 rice to water ratio by volume for long-grain.", "Fluff, never stir — breaks grains."],
      criticalControlPoints: ["Hot hold 140°F+", "Discard after 4-hour hold"],
      commonMistakes: ["Lifting lid during cook — steam escape", "Overwatering — gummy rice"],
      textureGuide: "Separate, fluffy grains that absorb gumbo without turning to paste.",
      colorGuide: "Bright white, steamy.",
      tasteGuide: "Clean, lightly salted — a canvas for gumbo.",
    },
    nutrition: { calories: 180, proteinG: 3, fatG: 1, carbsG: 40, sodiumMg: 120, servingSize: "4 oz portion" },
    costing: { suggestedMenuPrice: 3.5 },
  },
];
