/** Routes under Restaurant OS that require an authenticated session when auth is enabled. */
export const PROTECTED_OS_PREFIXES = [
  "/dashboard",
  "/inventory",
  "/recipes",
  "/restaurant-depot",
  "/weekly-reorder",
  "/freezer",
  "/walk-in-cooler",
  "/protein-prep",
  "/daily-prep",
  "/batch-calc",
  "/production-schedule",
  "/packaging",
  "/food-cost",
  "/profit-margin",
  "/portions",
  "/orders",
  "/menu-management",
  "/delivery-analytics",
  "/waste-log",
  "/vendors",
  "/employees",
  "/reporting",
  "/bookkeeping",
  "/financial-reports",
  "/tax-compliance",
  "/budgeting",
  "/cash-flow",
  "/insights",
] as const;
